# Generated by Django 6.0.4 on 2026-06-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_bundle_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_diet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_schedule',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
