# Generated by Django 6.0.5 on 2026-06-06 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_subscription_diet_order_subscription_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('paid', 'Sudah Dibayar'), ('processing', 'Diproses'), ('delivered', 'Dikirim'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.order')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
